// src/components/Comment.svelte
<section>
    <script src="https://giscus.app/client.js"
        data-repo="shyakocat/shyakocat.github.io-comments"
        data-repo-id="R_kgDOQywAvg"
        data-category="Announcements"
        data-category-id="DIC_kwDOQywAvs4C0h6_"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme={$mode === DARK_MODE ? 'dark' : 'light'}
        data-lang="zh-CN"
        crossorigin="anonymous"
        async>
    </script>
</section>

<script>
import { AUTO_MODE, DARK_MODE } from '@constants/constants.ts'
import { onMount } from 'svelte'
import { writable } from 'svelte/store';
import { getStoredTheme } from '@utils/setting-utils.ts'
const mode = writable(AUTO_MODE)
onMount(() => {
  mode.set(getStoredTheme())
})

function updateGiscusTheme() {
  const theme = document.documentElement.classList.contains('dark') ? 'dark' : 'light'
  const iframe = document.querySelector('iframe.giscus-frame')
  if (!iframe) return
  iframe.contentWindow.postMessage({ giscus: { setConfig: { theme } } }, 'https://giscus.app')
}

const observer = new MutationObserver(updateGiscusTheme)
observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] })

window.onload = () => {
  updateGiscusTheme()
}
</script>

// src/components/Comment.tsx
import Giscus from "@giscus/react";
import * as React from "react";

const id = "inject-comments";

// 获取 localStorage 中 theme 的值
function getSavedTheme() {
	return window.localStorage.getItem("theme");
}

// 获取系统主题
function getSystemTheme() {
	return window.matchMedia("(prefers-color-scheme: dark)").matches
		? "dark"
		: "light";
}

function getCurrentTheme() {
	const theme = getSavedTheme();
	return theme === "dark" || theme === "light" ? theme : getSystemTheme();
}

const Comments = () => {
	const [mounted, setMounted] = React.useState(false);
	const [theme, setTheme] = React.useState("light");

	React.useEffect(() => {
		setTheme(getCurrentTheme());
		// 监听主题变化
		const observer = new MutationObserver(() => {
			setTheme(getCurrentTheme());
		});
		observer.observe(document.documentElement, {
			attributes: true,
			attributeFilter: ["data-theme"],
		});

		// 取消监听
		return () => {
			observer.disconnect();
		};
	}, []);

	React.useEffect(() => {
		setMounted(true);
	}, []);

	return (
		<div id={id} className="w-full" style={{ height: "auto !important" }}>
			{mounted ? (
				<Giscus
					id={id}
					repo="shyakocat/shyakocat.github.io-comments"
					repoId="R_kgDOQywAvg"
					category="Announcements"
					categoryId="DIC_kwDOQywAvs4C0h6_"
					mapping="title"
					reactionsEnabled="1"
					emitMetadata="0"
					inputPosition="top"
					lang="zh-CN"
					loading="lazy"
					theme={theme}
				/>
			) : null}
		</div>
	);
};

export default Comments;
